apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafestatic
  namespace: cafe-static-argo  # <--- Added this line
  labels:
    app: cafestatic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafestatic
  template:
    metadata:
      labels:
        app: cafestatic
    spec:
      containers:
      - name: cafestatic
        image: pranesh6/cafe-static-website:latest
        ports:
        - containerPort: 80

